package tests;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import task.VigenereCipherBreaker;

public class TestVigenereCipherExtra {
	/**
	 * Test Case Number 1
	 */
	@Test
	public void testCase1() {
		VigenereCipherBreaker vcb = new VigenereCipherBreaker();
		vcb.setCipherText("PFPWWLZPEVHXTXONMYLHPSYTGZXCZBNICEVHRVYCDPPOULXSL"
				+ "HTCESWZQZCSWSEPBAXSLBOMDECYCESOAHCPOTWLCSTSCPDVAPCTBPESOUJ"
				+ "LNHZXSLHOSAPOSALJGAVTFAWLDZJLVPIDLVTPBJIESOAPLFUOXPCWZXSPCU"
				+ "PJNIYIQZFNVTPTHROTPLPTPJLXSLHSSGPWZWECCUKPCHOEYOSHXS");
		assertEquals(5, vcb.computeKeyLength());
		vcb.decipherText();
		assertEquals("HELLO", vcb.getKey());
		assertEquals(
				"IBELIEVETHATIMAGINATIONISSTRONGERTHANKNOWLEDGETHATMYTHISMOREPOTENTTHANHISTORY"
						+ "THATDREAMSAREMOREPOWERFULTHANFACTSTHATHOPEALWAYSTRIUMPHSOVEREXPERIENCE"
						+ "THATLAUGHTERISTHEONLYCUREFORGRIEFANDIBELIEVETHATLOVEISSTRONGERTHANDEATH",
				vcb.getPlainText());
	}

	/**
	 * Test Case Number 2
	 */
	@Test
	public void testCase2() {
		VigenereCipherBreaker vcb = new VigenereCipherBreaker();
		vcb.setCipherText("VVVXSQWPSNJMUMJOKKLGFQAVEXAHWRVTMFXVVRKAJTVMFLOPHYWJDSTXKAGFVVTPHKYEPP"
				+ "JOKPSWACJVSIGGVOLXLVMQPVCMGOGMFLAKENVRMIUAKTKVHIXCFJZRAHWFHLIUMHCIRFWGFOETIUNE"
				+ "QVJWEHOSJWVQFYWKYMPGQHWISOPKHYFYV");
		assertEquals(7, vcb.computeKeyLength());
		vcb.decipherText();
		assertEquals("CORRECT", vcb.getKey());
		assertEquals("THEGOODNEWSISTHATTHEMOMENTYOUDECIDETHATWHATYOUKNOWISMOREIMPORTANTTHANWHATYOU"
				+ "HAVEBEENTAUGHTTOBELIEVEYOUWILLHAVESHIFTEDGEARSINYOURQUESTFORABUNDANCESUCCESSCOMES"
				+ "FROMWITHINNOTFROMWITHOUT", vcb.getPlainText());
	}

	/**
	 * Test Case Number 3
	 */
	@Test
	public void testCase3() {
		VigenereCipherBreaker vcb = new VigenereCipherBreaker();
		vcb.setCipherText("ATVDVKGSTBPRPOWLJYRGJXDJPWSDUBZQKNEUWLJTPBBOEQUWLWUBOQIOVTYINTZIWNSXKPWNTZ"
				+ "QMOYPWUFQUVLJXDCGFSRKZMEORZRDVYUMGXEAOFWLJTFWDRAWGWSUAAQCLADMLRYUAPNCKZCQHNZPACREN"
				+ "QVXUGPVOELUJLRLEVCFSLMGYIWNHDNDOEQDRIZOICIOVJDZJKCMANOOGEYYCOICSSZQXVXOZGXERTYKIYN"
				+ "LZRDITWSMSZOMBUYPTKIWKPVHYUSJDRIYHVMYNFFDCNZDQUVFBNOJWUTBQOSLADRINPBHYUJPWLJNLIMBE"
				+ "BNKEWJHVMDHBVWMRKFWDGIMNQSYNHDNDOQWWMYHHKTSNUJHWPEHOJSN");
		assertEquals(11, vcb.computeKeyLength());
		vcb.decipherText();
		assertEquals("ABCDEFGHIJK", vcb.getKey());
		assertEquals(
				"ASTARFALLSFROMTHESKYANDINTOYOURHANDSTHENITSEEPSTHROUGHYOURVEINSANDSWIMS"
						+ "INSIDEYOURBLOODANDBECOMESEVERYPARTOFYOUANDTHENYOUHAVETOPUTITBACKINTOTHESKYAND"
						+ "ITISTHEMOSTPAINFULTHINGYOUWILLEVERHAVETODOANDTHATYOUHAVEEVERDONEBUTWHATISYOURS"
						+ "ISYOURSWHETHERITISUPINTHESKYORHEREINYOURHANDSANDONEDAYITWILLFALLFROMTHESKYAND"
						+ "HITYOUINTHEHEADREALHARDANDTHATTIMEYOUWILLNOTHAVETOPUTITBACKINTHESKYAGAIN",
				vcb.getPlainText());
	}
}
